In [5]:
#importing libraries

import numpy as np
import pandas as pd


In [94]:
# mouting the google drive and creating a pandas dataframe of hotels booking data

working_dir = '/content/drive/MyDrive/Capstone project/EDA/Data/Hotel Bookings.csv'
hotel_df = pd.read_csv(working_dir)

In [95]:
# a glance view of the dataframe

hotel_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   hotel                           119390 non-null  object 
 1   is_canceled                     119390 non-null  int64  
 2   lead_time                       119390 non-null  int64  
 3   arrival_date_year               119390 non-null  int64  
 4   arrival_date_month              119390 non-null  object 
 5   arrival_date_week_number        119390 non-null  int64  
 6   arrival_date_day_of_month       119390 non-null  int64  
 7   stays_in_weekend_nights         119390 non-null  int64  
 8   stays_in_week_nights            119390 non-null  int64  
 9   adults                          119390 non-null  int64  
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64  
 12  meal            

In [96]:
hotel_df.shape

(119390, 32)

In [97]:
# inspection of the first five columns

hotel_df.head(5)

hotel  is_canceled  ...  reservation_status  reservation_status_date
0  Resort Hotel            0  ...           Check-Out               2015-07-01
1  Resort Hotel            0  ...           Check-Out               2015-07-01
2  Resort Hotel            0  ...           Check-Out               2015-07-02
3  Resort Hotel            0  ...           Check-Out               2015-07-02
4  Resort Hotel            0  ...           Check-Out               2015-07-03

[5 rows x 32 columns]

In [98]:
# checking if the data has null values
hotel_df.isnull().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company         

In [99]:
# Dropping agent and company's columns as they have a lot of null values
hotel_df.drop(columns=['agent','company'],inplace=True)

In [100]:
# checking the unique values in the children column and calculating the number of NA values

hotel_df['children'].unique()


array([ 0.,  1.,  2., 10.,  3., nan])

In [108]:
# replacing the NA values with zero 
hotel_df['children'].replace(np.NaN,0,inplace = True)
hotel_df['children'] = hotel_df['children'].astype('int64')

In [109]:
hotel_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 30 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   hotel                           119390 non-null  object 
 1   is_canceled                     119390 non-null  int64  
 2   lead_time                       119390 non-null  int64  
 3   arrival_date_year               119390 non-null  int64  
 4   arrival_date_month              119390 non-null  object 
 5   arrival_date_week_number        119390 non-null  int64  
 6   arrival_date_day_of_month       119390 non-null  int64  
 7   stays_in_weekend_nights         119390 non-null  int64  
 8   stays_in_week_nights            119390 non-null  int64  
 9   adults                          119390 non-null  int64  
 10  children                        119390 non-null  int64  
 11  babies                          119390 non-null  int64  
 12  meal            

In [102]:
#checking unique values in the adults column

hotel_df['adults'].unique()

array([ 2,  1,  3,  4, 40, 26, 50, 27, 55,  0, 20,  6,  5, 10])

In [103]:
#checking unique values in the babies column

hotel_df['babies'].unique()

array([ 0,  1,  2, 10,  9])

In [110]:
# getting instances where adults,children and babies column contain 0 in the single row

filt = (hotel_df['adults'] == 0) & (hotel_df['children'] == 0) & (hotel_df['babies'] == 0)
hotel_df.loc[filt ,'adults':'babies']

adults  children  babies
2224         0         0       0
2409         0         0       0
3181         0         0       0
3684         0         0       0
3708         0         0       0
...        ...       ...     ...
115029       0         0       0
115091       0         0       0
116251       0         0       0
116534       0         0       0
117087       0         0       0

[180 rows x 3 columns]

In [114]:
# creating a new column of total family members

hotel_df['total_family_members'] = hotel_df['adults'] + hotel_df['children'] + hotel_df['babies']

In [116]:
hotel_df.drop(columns='Total_family_members')

hotel  is_canceled  ...  reservation_status_date  total_family_members
0       Resort Hotel            0  ...               2015-07-01                     2
1       Resort Hotel            0  ...               2015-07-01                     2
2       Resort Hotel            0  ...               2015-07-02                     1
3       Resort Hotel            0  ...               2015-07-02                     1
4       Resort Hotel            0  ...               2015-07-03                     2
...              ...          ...  ...                      ...                   ...
119385    City Hotel            0  ...               2017-09-06                     2
119386    City Hotel            0  ...               2017-09-07                     3
119387    City Hotel            0  ...               2017-09-07                     2
119388    City Hotel            0  ...               2017-09-07                     2
119389    City Hotel            0  ...               2017-09-07                     2

[119390 rows x 31 columns]